### ISSUE TITLE
project name must be `null.ldtk` on macOS

### ISSUE THREAD

**Issue by mempler** [Cammin/LDtkTilesetExporter#1]
For some reason, a project must be named `null.ldtk` instead of any project name for this to work.

Also, permission issue, the `ExportTilesetDefinitionMac.sh` script does not have the `Execute` permission flag `chmod +x` and must be manually adjusted.

**Comment by Cammin** [comment]
I am unable to make fixes and test for MacOS issues. Though I'm happy to accept any pull requests 🙂

**Comment by cyanlink** [comment]
also had this, i am trying to investigate it today

**Comment by cyanlink** [comment]
so it turns out the process is located but process.MainWindowTitle is always null while MainWindowHandle is a 0x0 pointer. Because all of these are not supported on non-Windows OS. Trying xamarin iOS & Mac
Edit geez this is super nasty. Like there is no way at all. The best solution would be LDtk supporting command arguments as already proposed here by @Cammin  : 
https://github.com/deepnight/ldtk/issues/965

**Comment by cyanlink** [comment]
What about an alternative solution: since the custom command is per project, we can write the project name from unity side as an command line argument.

**Comment by Cammin** [comment]
Yeah, it's super tricky. This is the only solution I could try to get information about the current project. Believe you me, I've tried exploring for an elegant solution, but I've needed to resort to getting a process's window header 😅

But if you have some other ideas on how to get the name of the project we want to execute the command upon, I'd be happy to experiment on that front more.

And yeah, for mac users, it will always be the string "null".

A temporary workaround is to name your LDtk project as "null.ldtk" and that should work, I've had other users have some success with that 🙂

**Comment by cyanlink** [comment]
AFAIK there is no way to get the **other** window's title on Mac from a Csharp console app at all. But I don't get it, since the custom command is stored in the .ldtk project file itself (that is, already on a per project basis), then why don't we just get the filename from the Unity editor script side, and write it as an additional argument when we add the command from Unity inspector?

**Comment by Cammin** [comment]
You're right, I never thought about that 😅 
Albeit if a project was renamed, the command would need to be re-pasted, but that could be error-message handled anyways.
I'll keep a note of this for a future update

**Comment by Cammin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The command that we paste into ldtk's custom command can just include an arg of the project name to solve the problem of getting a window header](https://trello.com/c/jluLTrBc/1040-the-command-that-we-paste-into-ldtks-custom-command-can-just-include-an-arg-of-the-project-name-to-solve-the-problem-of-getting)

**Comment by Cammin** [comment]
Hi, I fixed this :) 
A project name is now specified as an arg in the custom command. No more dirty window process searching!
It will come in the next update, but I am waiting until LDtk 1.5 is released before I prep the update's release. I'll update back here when I release a new update to the importer.

**Comment by pdom0327** [comment]
The current script does not carry the argument properly. Changing the name to null.ldtk will not resolve the issue now.
You need to run the script below directly from your ldtk project location.

`/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono /<UnityProjectFolder>/Library/LDtkTilesetExporter/ExportTilesetDefinition.exe "<LDtkProjectName>"`

**Comment by Cammin** [comment]
There's some outgoing mac fixes that I haven't published yet, so that can be re-evaluated after the update is out. I'm looking to have it out by the end of the weekend, fingers crossed 🙂

**Comment by juliusnugraha** [comment]
I love this app.. I'm using mac and you guys helped to fixed.. thanks

> There's some outgoing mac fixes that I haven't published yet, so that can be re-evaluated after the update is out. I'm looking to have it out by the end of the weekend, fingers crossed 🙂

hope fixed for macs.. all four side fingers crossed.

**Comment by Cammin** [comment]
Thanks, the update should be out soon. It's become a bit of a bigger update than normal. You can track what I'm up to on the importer discord server or ask any questions  and get a quick answer 🙂

**Comment by Cammin** [comment]
This should be fixed now. But let me know if it's still a problem!
