### ISSUE TITLE
No second arg!  on Mac OS

### ISSUE THREAD

**Issue by chenshun131** [Cammin/LDtkTilesetExporter#3]
Executing:../../Library/LDtkTilesetExporter/ExportTilesetDefinitionMac.sh "t1"
ExportTilesetDefinition version 1.5.2.0
Working from /Users/chenshun/Desktop/workspace/unity/Project/LDIKStudy/Assets/Resource
Didn't operate any files. No second arg!
There needs to be a project file name arg in the command.

**Comment by chenshun131** [comment]
![截屏2024-05-02 18 41 14](https://github.com/Cammin/LDtkTilesetExporter/assets/7045134/9436e903-234c-427f-8fa5-f2b734cdb8cf)
This problem does not exist on windows。

**Comment by Cammin** [comment]
Hi, I'm working towards a major update to the importer, we can re-evaluate if there's still a problem when the time comes 🙂

**Comment by Cammin** [comment]
Hi, there's a fix for this now, but let me know if it still doesn't work and I can reopen the issue.
