### ISSUE TITLE
Doesn't work save command on MacOS

### ISSUE THREAD

**Issue by Wazti** [Cammin/LDtkTilesetExporter#4]
Trying add ldkt to my Unity project
After adding a command to ldtk, it doesnt parse levels and error with command is showed in unity (that command isn't added)
<img width="453" alt="Снимок экрана 2024-06-03 в 16 10 44" src="https://github.com/Cammin/LDtkTilesetExporter/assets/40702479/2c5a7f2c-d55f-482e-af5e-1299d0e6ce0a">
<img width="701" alt="Снимок экрана 2024-06-03 в 16 10 39" src="https://github.com/Cammin/LDtkTilesetExporter/assets/40702479/4fea19e0-1b4a-4018-9aea-fc78dbe47634">

Unity 2022.3.31f1
Ldtk 1.5.3

**Comment by Cammin** [comment]
For your command, you'll need that "$1" added to the end of it like it's pointing out.
Join the discord and I can give some greater hands-on help. Also there're previous resources for other mac users having some issues in there 🙂
